{{- if .Values.postgres.service }}
{{- with .Values.postgres.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" $ }}
  labels:
    {{- include "postgres.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "postgres.selectorLabels" $ | nindent 4 }}
  type: {{ .type }}
  {{- if .ports }}
  ports:
    {{- toYaml .ports | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
